language: node_js
node_js:
  - '6'
  - '5'
  - '4'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.8
env:
  - CXX=g++-4.8
before_install:
  - npm explore npm -g -- npm install node-gyp@latest

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
